name: Test
on:
  workflow_dispatch:
    
jobs:
 job1111:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout
    uses: actions/checkout@v2 # 将代码拷贝到虚机中
    with:
     ref: master
     persist-credentials: false
  - run: |
      pwd #/home/runner/work/learn-github-actions/learn-github-actions
      ls -lt
  - uses: actions/upload-artifact@v2
    with:
     name: test-artifact
     path: ./
 job2222:
  runs-on: ubuntu-latest
  needs: job1111
  steps: 
  - run: pwd #/home/runner/work/learn-github-actions/learn-github-actions
  - uses: actions/download-artifact@v2
    with:
     name: test-artifact
  - run: ls -lt
  - run: npm -v
  - run: java -version #openjdk version "11.0.11" 2021-04-20
  - name: Deploy to Server
    uses: easingthemes/ssh-deploy@main
    env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "src/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
