name: Test
on:
  watch:
    types: started
    
jobs:
 job1111:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout
    uses: actions/checkout@v2 # 将代码拷贝到虚机中
    with:
     ref: master
     persist-credentials: false
  - name: shellTest
    run: ls -lt
 job2222:
  runs-on: ubuntu-latest
  steps: 
  - name: shellTest
  - run: pwd
  - run: ls -lt
  - run: npm -v
