name: Test
on:
  workflow_dispatch:
    
jobs:
 job1111:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout
    uses: actions/checkout@v2 # 将代码拷贝到虚机中
    with:
     ref: master
     persist-credentials: false
  - run: pwd
  - run: java -version
 job2222:
  runs-on: ubuntu-latest
  steps: 
  - run: pwd #/home/runner/work/learn-github-actions/learn-github-actions
  - run: ls -lt
  - run: npm -v
